### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shanow7** [mez0cc/linky#7]
python3 -r install requirements.txt
Unknown option: -r
usage: python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
┌─[✗]─[user@parrot]─[~/Desktop/linky]
└──╼ $python3 install -r requirements.txt
python3: can't open file 'install': [Errno 2] No such file or directory

can you help me?

**Comment by mez0cc** [comment]
Your command is trying to install `install` as a package. You need the `-r` afterwards:

```python3 install -r requirements.txt```

**Comment by shanow7** [comment]
python3 install -r requirements.txt
python3: can't open file 'install': [Errno 2] No such file or directory

**Comment by mez0cc** [comment]
Dude,
```
python3 install -r requirements.txt
python3: can't open file 'install': [Errno 2] No such file or directory

python3 install -r requirements.txt
python3: can't open file 'install': [Errno 2] No such file or directory

nothing has changed
```
You need to switch `python3` for `pip3`.

**Comment by shanow7** [comment]
how can I do that?

**Comment by mez0cc** [comment]
Run: `pip3 install -r requirements.txt`

**Comment by shanow7** [comment]
thx :)
I've next problem

_Please add the cookie to a file_

where I must add this file?

**Comment by mez0cc** [comment]
add the `li_at` cookie into `cookie.txt`.
